[features]
seeds = false
skip-lint = false
[programs.localnet]
ned_wallet_vault = "NEDSye1RDFLw6kmgHaaaF57NjNdD9WMHGvoyuLX9Kg6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/marco/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
