[features]
seeds = false
skip-lint = false
[programs.localnet]
ned_wallet_program = "5J8oWg8KbXvNqe64tpzCsbUdtVpBiHn6roFRrQ73FNMQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marco/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
